apply plugin: 'java-library'
apply plugin: 'kotlin'

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
    api 'com.fasterxml.jackson.core:jackson-databind:2.17.2'
    api 'com.fasterxml.jackson.core:jackson-core:2.17.2'
    api 'com.fasterxml.jackson.core:jackson-annotations:2.17.2'

    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${rootProject.ext.kotlin_version}"
}
