apply plugin: 'application'
apply plugin: 'kotlin'
apply plugin: 'org.openjfx.javafxplugin'

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
    kotlinOptions {
        jvmTarget = '11'
    }
}

application {
    mainClass = 'org.happypeng.sumatora.desktop.LauncherKt'
}

javafx {
    version = '17'
    modules = ['javafx.controls', 'javafx.fxml']
}

dependencies {
    implementation project(':core')
    implementation "org.xerial:sqlite-jdbc:3.49.0.0"
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:${rootProject.ext.kotlin_version}"
}
